### ISSUE TITLE
(bedrock): s3-data-source - add hierarchical and semantic chunking support

### ISSUE THREAD

**Issue by aws-rafams** [awslabs/generative-ai-cdk-constructs#648] opened 2024-08-21 11:55 UTC
### Describe the feature
It would be useful to add support to hierarchical and semantic chunking, besides the already supported, fixed size.
https://github.com/awslabs/generative-ai-cdk-constructs/blob/16e15cd81e409bb45788d50d673071f44cd24210/src/cdk-lib/bedrock/s3-data-source.ts#L32-L50
https://docs.aws.amazon.com/bedrock/latest/userguide/kb-chunking-parsing.html#kb-hiearchical-chunking
https://docs.aws.amazon.com/bedrock/latest/userguide/kb-chunking-parsing.html#kb-semantic-chunking

### Use Case

Semantic chunking improves retrieval accuracy by focusing on the semantic content rather than just syntactic structure. 

### Proposed Solution

modify `s3-data-source.ts` module

### Other Information

Semantic and Hierarchical Chunking are already supported by L1 construct
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_bedrock.CfnDataSource.ChunkingConfigurationProperty.html#chunkingstrategy

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by krokoko** [comment] 2024-08-21 12:44
closing as duplicate of https://github.com/awslabs/generative-ai-cdk-constructs/issues/587 
The new chunking strategies and associated parameters (see [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrock-datasource-chunkingconfiguration.html)) are available in cfn but not in cdk yet. They should be added in an upcoming release, we will then implement it.

**Closed by krokoko** 2024-08-21 12:44 UTC
Labels: duplicate
