### ISSUE TITLE
Knowledge base: support to invoke LLM on other region

### ISSUE THREAD

**Issue by statefb** [awslabs/generative-ai-cdk-constructs#522] opened 2024-06-18 23:47 UTC
### Describe the feature

The current implementation library does not support invoking AI models from a different region than the one where the Knowledge Base (KB) and other resources are deployed.

### Use Case

claude3 only supports limited regions.

### Other Information

I may be able to implement this feature request, but I have other preoritized tasks, so I cannot promise the timeline to develop it.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by krokoko** [comment] 2024-10-02 16:54
Closing this as the feature it is a duplicate of the current work with inference profiles

**Closed by krokoko** 2024-10-02 16:54 UTC
Labels: enhancement, backlog
