### ISSUE TITLE
(bedrock): Class Agent / Interface: AgentProps doesn't detect changes on parameter "instruction", preventing CDK Deploy from updating.

### ISSUE THREAD

**Issue by carlosicc** [awslabs/generative-ai-cdk-constructs#789] opened 2024-11-06 18:33 UTC
### Describe the bug

When modifying the Agent Prompt (parameter instruction for Interface AgentProps) in the Agent class, the CDK project doesn't detect any changes; e.g. `cdk deploy stack >>> No changes detected`. This means I have to edit manually the Agent's instruction or prompt, i.e. via CLI or Console, instead of running a simple CDK DEPLOY. 

Example:
```python
agent_instruction = """
You are a friendly virtual assistant for our department store...
... [truncated]
"""

# Create Agent. Hard-coded params: LLM Model. 
agent = bedrock.Agent(self, 'Agent01',
    name='virtual-assistant-agent',
    foundation_model=bedrock.BedrockFoundationModel.ANTHROPIC_CLAUDE_3_5_SONNET_V1_0,
    alias_name="virtual-assistant-agent-v1",
    instruction=agent_instruction,
    knowledge_bases=[kb],
    should_prepare_agent=True
)
``` 

So, if I modify the value of `agent_instruction`, `CDK DEPLOY` doesn't detect this.

### Expected Behavior

CDK DEPLOY should detect and redeploy stack.

### Current Behavior

CDK Deploy doesn't detect any changes. Resources (e.g. Bedrock agent) need manual intervention.

### Reproduction Steps

Deploy the stack with X agent_instruction.
Modify the agent_instruction
Redeploy stack

### CDK CLI Version

2.156.0

### Node.js Version

v20.5.0

### OS

MacOS Sonoma Version 14.7 (23H124)

### Language

Python

### Region experiencing the issue

us-west-2

### Code modification

N/A

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by aws-rafams** [comment] 2024-11-09 21:41
Hi Carlos! Thanks for reaching out!

Unfortunately I did not manage to replicate the issue. Could you share with us the library version you're using?
Could you also run `cdk diff` after saving a change to the instruction parameter and send us a screenshot?

Thanks!

**Comment by krokoko** [comment] 2024-11-20 02:11
Hi @carlosicc thanks for reporting this issue. I am not able neither to replicate. Tested by creating an agent with an initial instruction, deploy, update the instruction, re-deploy. Changes are correctly detected. Could you please try again with the latest version of the library ? Thank you

**Comment by krokoko** [comment] 2024-11-20 20:21
Closing as we are not able to reproduce, @carlosicc feel free to reopen if you are still facing the issue and can provide a sample stack. Thank you !

**Closed by krokoko** 2024-11-20 20:21 UTC
Labels: bug, needs-triage, cannot-reproduce

**Comment by carlosicc** [comment] 2024-12-02 17:38
My sincere apologies for not updating this ticket before, as I wanted some time to test these same versions and redeploy. 

Info for the community, just in case this helps anyone:

After redeploying my Bedrock CDK stack, I realized I was wrong and the behaviour is the expected. My confusion comes from the AWS documentation ([link here](https://docs.aws.amazon.com/bedrock/latest/userguide/agents-edit.html)), as it doesn't say "_you have to publish a new version of the Bedrock agent, if you edit the current one_". I incorrectly assumed the current version would be modified, instead of needing to create a new Agent Version, and the new changes (i.e. Agent's prompt description) will take effect (in the new version).
